refactor: Break out loan directory in maple core to be a submodule dapptools project
maple-labs/loan pull request #1
Opened 2021-08-05 15:20 UTC by JGcarv

2021-08-05 21:22 UTC, deluca-mike requested changes

2021-08-05 21:22 UTC, deluca-mike commented on contracts/Loan.sol
> +        return Util.calcMinAmount(address(_globals(superFactory)), address(collateralAsset), address(liquidityAsset), liquidationAmt);
This is going to have to be changed since I am going to revert the Util library change that went from `IMapleGlobals` to `address` as the first param. As well as pulling the new `util` commit.

2021-08-05 21:22 UTC, deluca-mike commented on contracts/interfaces/ILoan.sol
> +import { IBasicFundsTokenFDT } from "../../modules/funds-distribution-token/contracts/interfaces/IBasicFundsTokenFDT.sol";
We can put these in the same block, no empty line between, and then aligned.

2021-08-05 21:22 UTC, deluca-mike commented on contracts/LoanFactory.sol
> +interface IMapleGlobalsLike {
Can this be imported from `Interfaces.sol`?

2021-08-05 21:22 UTC, deluca-mike commented on contracts/libraries/LoanLib.sol
> +    IMapleGlobals as IMapleGlobalsLike,  // NOTE: Necessary for https://github.com/ethereum/solidity/issues/9278
👍

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test.json
> +[{"inputs":[],"name":"UNISWAP_ROUTER","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nextPa
What is this? 🤔

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +contract LoanTest is DSTest {
I think it's best to leave this uncommented, and just not include the file in the ci and dev configs so it does not get built (or tested).

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/standard.json
> +{"language": "Solidity", "sources": {"contracts/LoanFactory.sol": {"urls": ["contracts/LoanFactory.sol"]}, "contracts/Loan.sol": {"urls": ["contracts/Loan.sol"]}, "contracts/test/LoanFactory.t copy.s
No need for this.

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/LoanFactory.t.sol
> +}
```suggestion
    }

}
```

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/LoanFactory.t.sol
> +}
```suggestion
    }

}
```

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/LoanFactory.t.sol
> +    function test_createLoan_invalid_subFactories() public {
```suggestion
    function test_createLoanWithInvalidSubFactories() public {
```

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/LoanFactory.t.sol
> +    function test_createLoan_invalid_calcs() public {
```suggestion
    function test_createLoanWithInvalidCalcs() public {
```

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/LoanFactory.t.sol
> +    function test_createLoan_invalid_assets() public {
```suggestion
    function test_createLoanWithInvalidAssets() public {
```

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/LoanFactory.t.sol
> +    function test_createLoan_invalid_specs() public {
```suggestion
    function test_createLoanWithInvalidSpecs() public {
```

2021-08-05 21:22 UTC, deluca-mike commented on contracts/test/LoanFactory.t.sol
> +    function test_createLoan_successfully() public {
```suggestion
    function test_createLoan() public {
```

2021-08-06 00:23 UTC, lucas-manuel commented on contracts/Loan.sol
> +        return Util.calcMinAmount(address(_globals(superFactory)), address(collateralAsset), address(liquidityAsset), liquidationAmt);
I'll leave this for now and then make the change once the Util PR is merged

2021-08-06 00:24 UTC, lucas-manuel commented on contracts/LoanFactory.sol
> +interface IMapleGlobalsLike {
Yeah it can actually will do

2021-08-06 00:26 UTC, lucas-manuel commented on contracts/test.json
> +[{"inputs":[],"name":"UNISWAP_ROUTER","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"nextPa
Not supposed to be here, I'll delete

2021-08-06 00:29 UTC, lucas-manuel commented on contracts/test/standard.json
> +{"language": "Solidity", "sources": {"contracts/LoanFactory.sol": {"urls": ["contracts/LoanFactory.sol"]}, "contracts/Loan.sol": {"urls": ["contracts/Loan.sol"]}, "contracts/test/LoanFactory.t copy.s
Yeah deleted, I remember it was from when we were debugging the bytecode for when we were trying to figure out libs

2021-08-06 16:24 UTC, deluca-mike commented on contracts/Loan.sol
> +        return Util.calcMinAmount(address(_globals(superFactory)), address(collateralAsset), address(liquidityAsset), liquidationAmt);
https://github.com/maple-labs/util/pull/5

2021-08-06 16:29 UTC, deluca-mike requested changes
Just a new lne at the end of a file, and taking the soon-to-be merged latest Util

2021-08-06 16:29 UTC, deluca-mike commented on config/prod.json
> +}
New line at end of file

2021-08-06 18:40 UTC, merged