Sc 4372 loan add missing unit tests for accept new terms
maple-labs/loan pull request #121
Opened 2021-12-20 17:49 UTC by edag94

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog
Added tests for _acceptNewTerms

## Function Signature Changes

## Features

## Events

2021-12-20 19:00 UTC, lucas-manuel requested changes
LGTM, small changes

2021-12-20 19:48 UTC, lucas-manuel commented
Also can you change the title to:

test: Add missing unit tests for `acceptNewTerms` (SC-4372)

2021-12-21 05:56 UTC, deluca-mike commented on contracts/test/MapleLoanInternals.t.sol
> +        }
I'm not convinced you need to test this given that this is tested as part of `test_acceptNewTerms_validRefinancer` above. It's not bad, just redundant, and may throw someone off.

2021-12-21 16:53 UTC, lucas-manuel approved these changes

2021-12-21 16:53 UTC, lucas-manuel approved these changes

2021-12-21 17:30 UTC, merged