feat: Added deadlines to refinancing and allowed pool delegates to explicitly reject new terms  (SC-4886)
maple-labs/loan pull request #143
Opened 2022-03-03 20:01 UTC by vbidin

# Description
Added additional functionality to the `MapleLoan` contract which allows all refinance proposals to include deadlines up to which they can be accepted by the pool delegate, and added functionality that allows the borrower or lender to explicitly reject the terms of the refinancing.

# Integrations Checklist

- [x] Have any function signatures changed? If yes, outline below.
- [x] Have any features changed or been added? If yes, outline below.
- [x] Have any events changed or been added? If yes, outline below.
- [x] Has all documentation been updated?

# Changelog

## Function Signature Changes
Updated the following functions to include the `deadline` parameter in their signature:
- `acceptNewTerms()`
- `proposeNewTerms()`

## Features
- Added a `deadline` parameter to the `acceptNewTerms()` and `proposeNewTerms()` functions, and introduced a check that prevents the terms from being accepted when calling `acceptNewTerms()` after the deadline has elapsed.
- Added an additional function called `rejectNewTerms()` that allows pool delegates to explicitly reject terms of the proposed refinancing.

## Events
The following events had the `deadline` parameter added to their signature:
- `NewTermsAccepted`
- `NewTermsProposed`
An additional event was added which is emitted when anyone reject the proposed terms by calling `rejectNewTerms()`:
- `NewTermsRejected`

2022-03-03 22:29 UTC, lucas-manuel requested changes

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        try loan.proposeNewTerms(mockRefinancer, type(uint256).max, data) { assertTrue(false, "Non-borrower was able to propose new terms"); } catch { }
Lets use `vm.expectRevert` for all of these assertions

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/MapleLoanInternals.t.sol
> +        Refinancer differentRefinancer = new Refinancer();
Should use the same refiancer for this test

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/MapleLoanInternals.t.sol
> +        _loan.acceptNewTerms(address(_refinancer), deadline, calls);
Lets add success calls after all of these

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/MapleLoanInternals.t.sol
> +    function test_rejectNewTerms_commitmentMismatch() external {
Lets add cases for refinancer different address and different calls array

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        uint256 deadline = block.timestamp + 1;
Same here lets just use deadline = block.timestamp

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        loan.__setRefinanceCommitmentHash(keccak256(abi.encode(refinancer, type(uint256).max, data)));
Lets use deadline to be consistent with other tests

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        try loan.acceptNewTerms(refinancer, type(uint256).max, data, 1) { assertTrue(false, "Able to accept terms"); } catch { }
vm.expectRevert

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        deadline_           = constrictToRange(deadline_,           block.timestamp + 1, type(uint256).max);
block.timestamp instead of block.timestamp + 1 everywhere

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        loan.proposeNewTerms(address(refinancer), block.timestamp + 1, data);
block.timestamp

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        deadline_ = constrictToRange(deadline_, block.timestamp + 1, block.timestamp + MAX_TIME);
block.timestamp

2022-03-03 22:29 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        emit log_named_uint("deadline_", deadline_);
Get rid of logs

2022-03-03 23:59 UTC, xhad commented on contracts/MapleLoan.sol
> +    }
This is awesome thanks guys

2022-03-04 15:21 UTC, lucas-manuel requested changes

2022-03-04 15:21 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> -        loan.__setNextPaymentDueDate(block.timestamp + 1);
Lets leave these as is as they are out of scope

2022-03-04 15:21 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        uint256 deadline = block.timestamp;
All explicitly assigned deadlines should be `uint256 deadline = block.timestamp + 10 days`

2022-03-04 15:21 UTC, lucas-manuel commented on contracts/test/MapleLoanInternals.t.sol
> +        _loan.setNextPaymentDueDate(block.timestamp);
Lets leavea all of these as is as they are out of scope

2022-03-04 15:21 UTC, lucas-manuel commented on contracts/test/MapleLoanInternals.t.sol
> +        uint256 deadline = block.timestamp;
All explicitly assigned deadlines should be `uint256 deadline = block.timestamp + 10 days`

2022-03-04 15:21 UTC, lucas-manuel commented on contracts/test/MapleLoanInternals.t.sol
> +        Refinancer anotherRefinancer = new Refinancer();
Should not use `anotherRefinancer` at all in this test

2022-03-04 18:35 UTC, merged