feat: Add interest to storage (SC-5084)
maple-labs/loan pull request #149
Opened 2022-03-14 17:00 UTC by JGcarv

# Description

During  refinance there's a need to store both the partial principal and interest that are due according to the old loan terms, to be paid in the next due date.

This PR addresses this need,

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [x] Have any features changed or been added? If yes, outline below.

Added a `getRefinanceInstallment` that returns the pro-rata principal and interested
Added a `refinancePrincipal` and `refinanceInterest`

- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2022-03-14 18:02 UTC, lucas-manuel requested changes

2022-03-14 18:02 UTC, lucas-manuel commented on contracts/MapleLoanInternals.sol
> +        principal_ += _refinancePrincipal;
Actually lets move the addition of the values to both _getNextPaymentBreakdown and _getEarlyPaymentBreakdown

2022-03-15 06:59 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +        return _getInstallment(_principal, _endingPrincipal, _interestRate, timeSinceLastPayment, _paymentsRemaining);
Do we still want this after our discussion?

2022-03-15 20:32 UTC, lucas-manuel commented
Closing as contains these changes plus more

2022-03-15 20:32 UTC, closed without merging