feat: Flatten internals p2
maple-labs/loan pull request #168
Opened 2022-04-05 09:14 UTC by deluca-mike

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2022-04-06 21:38 UTC, lucas-manuel requested changes
Lets add back all test success calls that were removed from failure tests

2022-04-06 21:38 UTC, lucas-manuel commented on contracts/test/MapleLoanLogic.t.sol
> +        _loan.__setDrawableFunds(_defaultAmounts[1]);
Why are we no longer setting collateral?

2022-04-06 21:38 UTC, lucas-manuel commented on contracts/test/MapleLoanLogic.t.sol
> +        vm.expectRevert("ML:ANT:COMMITMENT_MISMATCH");
New line

2022-04-07 17:18 UTC, deluca-mike commented on contracts/test/MapleLoanLogic.t.sol
> +        _loan.__setLender(address(this));
I will add TODOs everywhere that an actor is `address(this)`

2022-04-07 17:21 UTC, deluca-mike commented on contracts/test/MapleLoanLogic.t.sol
> +        _loan.__setDrawableFunds(_defaultAmounts[1]);
Because no collateral is needed until the collateral required is increased in the tests. Also, `_defaultAmounts[0]` is 0. Really, all these setUps with `_defaultXXX` are suboptimal and painful.

2022-04-07 20:43 UTC, merged