feat: Create LoanProxyFactory contract with unit testing for instantiation (SC-3812)
maple-labs/loan pull request #22
Opened 2021-09-14 12:52 UTC by satyamakgec

We need to finalize who is going to upgrade the loan for whom.

TODO: 
- Testing

2021-09-15 14:46 UTC, lucas-manuel requested changes
Nice PR, some formatting changes then will do another sweep

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +import { Borrower }         from "./accounts/Borrower.sol";
```js
import { DSTest }               from "../../modules/ds-test/src/test.sol";
import { MockImplementationV1 } from "../../modules/proxy-factory/contracts/test/mocks/Mocks.sol";

import { MapleLoanFactory } from "../MapleLoanfactory.sol";

import { Borrower } from "./accounts/Borrower.sol";
import { Governor } from "./accounts/Governor.sol";
```

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +contract MapleGlobals {
MapleGlobalsMock

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +    address _governor;
Make public variable

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +    }
Remove function because of public var

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +    Borrower bow;
Alphabetical based on Contract type then variable name: https://github.com/maple-labs/smart-contract-standards/blob/main/sections/style-guide.md#declarations

Also aligned

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +    address migrator               = address(999);
Should use `address(1)` `address(2)` ... etc

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +    }
```js
function test_registerImplementation() public {
    assertTrue(!notGov.try_mapleLoanfactory_registerImplementation(address(mapleLoanFactory), 1, implementationAddress1, initializer1), "Should fail to register: Invalid governor");
    assertTrue(   !gov.try_mapleLoanfactory_registerImplementation(address(mapleLoanFactory), 0, implementationAddress1, initializer1), "Should fail to register: Invalid version");
    assertTrue(   !gov.try_mapleLoanfactory_registerImplementation(address(mapleLoanFactory), 1, address(0),             initializer1), "Should fail to register: Invalid implementation address");
    assertTrue(    gov.try_mapleLoanfactory_registerImplementation(address(mapleLoanFactory), 1, implementationAddress1, initializer1), "Should not fail to register");
    assertTrue(   !gov.try_mapleLoanfactory_registerImplementation(address(mapleLoanFactory), 1, implementationAddress2, address(0)),   "Should fail to register: Version already registered");  // Try to register again with the same version.

    assertEq(mapleLoanFactory.currentVersion(),                  1,                      "Incorrect state of currentVersion");
    assertEq(mapleLoanFactory.implementationOf(1),               implementationAddress1, "Incorrect state of implementationOf");
    assertEq(mapleLoanFactory.versionOf(implementationAddress1), 1,                      "Incorrect state of versionOf");
    assertEq(mapleLoanFactory.migratorForPath(1, 1),             initializer1,           "Incorrect state of migratorForPath");
}
```

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +        bow              = new Borrower();
`borrower`

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +        fakeGov          = new Governor();
`notGov`

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +        assertTrue( bow.try_mapleLoanFactory_createLoan(address(mapleLoanFactory), dummyArguments), "Should not fail to create loan");
Align using same method shown above

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +    }
Align with same method as above

2021-09-15 14:46 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +        assertTrue(     gov.try_mapleLoanfactory_enableUpgradePath(address(mapleLoanFactory), 1, 2, migrator), "Should not fail to uprade path");
Align with same method as above

2021-09-16 04:02 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +}
As per our standards, we should put `IMapleGlobalsLike` into `interfaces/Interfaces.sol` so that this file only contains one "class".

2021-09-16 04:31 UTC, deluca-mike requested changes

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +}
As per our standards, we should put `IMapleGlobalsLike` into `interfaces/Interfaces.sol` so that this file only contains one "class".

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +    IMapleGlobalsLike _globals;
```suggestion
    address _globals;
```
I'd argue it should even be
```suggestion
    address _mapleGlobals;
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        require(msg.sender == _globals.governor(), "MLF:UNAUTHORISED_EXECUTION");
```suggestion
        require(msg.sender == IMapleGlobalsLike(_globals).governor(), "MLF:UNAUTHORISED_EXECUTION");
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        require(_registerImplementation(version_, implementationAddress_), "MLF:FAIL_TO_REGISTER");
alignment

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        // Not allowing version equals to zero as 0 consider as no implementation exists with in the factory to create loans.
```suggestion
        // Version 0 reserved as "no version" since default `_currentVersion` is 0.
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        }
No point checking against 0, since there is no harm in the call
```suggestion
        // Set migrator for initialization, which understood as fromVersion == toVersion.
        _registerMigrator(version_, version_, initializer_);

```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        emit ImplementationRegistered(version_, implementationAddress_, initializer_);
```suggestion
        emit ImplementationRegistered(_currentVersion = version_, implementationAddress_, initializer_);
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        bytes32 salt_ = keccak256(abi.encodePacked(msg.sender, arguments_));
This is not the case. Salt needs to be based off `msg.sender` and some nonce, since two loans for the same borrower can have the same initialization arguments. Also, I think for this PR, we should not concern ourselves with the feature of lender-deterministic loan addresses just yet. We can save that added complexity (and nonces mapping) for a subsequent feature PR. Although, you can do it in this PR if you want.

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        emit UpgradePathEnabled(fromVersion_, toVersion_, migrator_);
No point checking against 0, since there is no harm in the call
```suggestion
        _registerMigrator(fromVersion_, toVersion_, migrator_);
        emit UpgradePathEnabled(fromVersion_, toVersion_, migrator_);
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        emit LoanDeployed(_currentVersion, loan_, arguments_);
Need to use _loanCount before incrementing, as it starts at 0.
```suggestion
        require(success_, "MLF:UNABLE_TO_INSTANTIATE");
        emit LoanDeployed(_currentVersion, _loans[_loanCount++] = loan_, arguments_);
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        emit LoanUpgraded(msg.sender, _versionOf[IProxied(msg.sender).implementation()], toVersion_, arguments_);
```suggestion
        require(_upgradeInstance(msg.sender, toVersion_, arguments_), "Some Error Message");
        emit LoanUpgraded(msg.sender, _versionOf[IProxied(msg.sender).implementation()], toVersion_, arguments_);
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +    mapping(uint256 => address) _loans;
As this is not a primitive contract, there is no need to make internals just to re-expose them as functions.
```suggestion
    uint256 public currentVersion;
    uint256 public loanCount;

    mapping(uint256 => address) public loans;
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +    }
No longer needed.

2021-09-16 04:31 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +}
New line at end of file.

2021-09-16 04:31 UTC, deluca-mike commented on contracts/interfaces/IMapleLoanFactory.sol
> +    event ImplementationRegistered(uint256 indexed version, address indexed implementationAddress, address initializer);
There was a mistake in the MDP that did not have `initializer` as `indexed`.
```suggestion
    event ImplementationRegistered(uint256 indexed version, address indexed implementationAddress, address indexed initializer);
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/interfaces/IMapleLoanFactory.sol
> +    function currentVersion() external view returns (uint256 currentVersion_);
I hesitate about `currentVersion` instead of `latestVersion` because it may give the impression that all loans are at `currentVersion` when really it means that all new loans will be created at `currentVersion`.

2021-09-16 04:31 UTC, deluca-mike commented on contracts/test/MapleLoanFactory.t.sol
> +}
New line needed at end of file.

2021-09-16 04:31 UTC, deluca-mike commented on contracts/test/accounts/Borrower.sol
> +    function try_mapleLoanFactory_createLoan(address mapleLoanfactory_, bytes calldata arguments_) external returns (bool ok_) {
Accounts need to be complete, so a `mapleLoanFactory_createLoan` is needed as well.

2021-09-16 04:31 UTC, deluca-mike commented on contracts/test/accounts/Governor.sol
> +contract Governor {
Accounts need to be complete, so we also need:
- `mapleLoanFactory_registerImplementation`
- `mapleLoanFactory_enableUpgradePath`
- `mapleLoanFactory_disableUpgradePath`

2021-09-16 04:31 UTC, deluca-mike commented on contracts/test/accounts/Governor.sol
> +    function try_mapleLoanfactory_registerImplementation(address mapleLoanFactory_, uint256 version_, address implementationAddress_, address initializer_) external returns (bool ok_) {
```suggestion
    function try_mapleLoanFactory_registerImplementation(address mapleLoanFactory_, uint256 version_, address implementationAddress_, address initializer_) external returns (bool ok_) {
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/test/accounts/Governor.sol
> +    function try_mapleLoanfactory_enableUpgradePath(address mapleLoanFactory_, uint256 fromVersion_, uint256 toVersion_, address migrator_) external returns (bool ok_) {
```suggestion
    function try_mapleLoanFactory_enableUpgradePath(address mapleLoanFactory_, uint256 fromVersion_, uint256 toVersion_, address migrator_) external returns (bool ok_) {
```

2021-09-16 04:31 UTC, deluca-mike commented on contracts/test/accounts/Governor.sol
> +    function try_mapleLoanfactory_disableUpgradePath(address mapleLoanFactory_, uint256 fromVersion_, uint256 toVersion_) external returns (bool ok_) {
```suggestion
    function try_mapleLoanFactory_disableUpgradePath(address mapleLoanFactory_, uint256 fromVersion_, uint256 toVersion_) external returns (bool ok_) {
```

2021-09-16 09:29 UTC, satyamakgec commented on contracts/MapleLoanFactory.sol
> +        bytes32 salt_ = keccak256(abi.encodePacked(msg.sender, arguments_));
I don't think nonces will work as you can't keep the nonces reserve if you are calculating off-chain. That leads to a non-deterministic loan address. Anyway, we can talk about this more in the future.

2021-09-16 09:45 UTC, satyamakgec commented on contracts/MapleLoanFactory.sol
> +        emit LoanDeployed(_currentVersion, loan_, arguments_);
I don't want to use the 0 as the loan index, As it is more convenient to have an index count equals to loan count.

2021-09-16 19:59 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        emit LoanDeployed(_currentVersion, loan_, arguments_);
Well, its really an array in the end of the day. 1-indexed arrays are weird. As devs, we're going to see that there have been 7 loans created, and we're naturally going to get `loans[0]` because its just a natural thing to do, and we'll be scratching our heads (even other devs who are not us) as to why 0 doesn't exist but 7 does. I just believe its an anti-pattern, similar to a http api that supports pagination, but the the default is `&page=1`.

2021-09-17 01:22 UTC, lucas-manuel requested changes
Tests look good, some small comments plus Natspec

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/interfaces/IMapleLoanFactory.sol
> +interface IMapleLoanFactory {
Need params for Natspec

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/MapleLoanFactory.sol
> +        require(_upgradeInstance(msg.sender, toVersion_, arguments_), "Upgrade Failed");
`"MLF:UPGRADE_FAILED"`

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/interfaces/IMapleLoanFactory.sol
> +interface IMapleLoanFactory {
Also with 
```
/**
 *
 */
```

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/interfaces/Interfaces.sol
> +     */
///

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +            dummyArguments), "Should fail to create loan: Version is not registered yet"
dummyArguments should be on line 84

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +        assertTrue( borrower.try_mapleLoanFactory_createLoan(address(loanFactory), dummyArguments), "Should not fail to create loan");
Extra space

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +
Extra line

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +            "Should fail to upgrade path: unauthorized"
Unauthorized

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +            "Should fail to disable upgrade path: unauthorized"
Unauthorized

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/test/MapleLoanFactory.t.sol
> +        assertTrue( governor.try_mapleLoanFactory_enableUpgradePath(address(loanFactory),  1, 2, migrator), "Should not fail to upgrade path");
`governor.mapleLoanFactory_enableUpgradePath`

2021-09-17 01:22 UTC, lucas-manuel commented on contracts/test/accounts/Governor.sol
> +        uint256 version_, address
address is on the wrong line

2021-09-17 13:46 UTC, deluca-mike commented on contracts/interfaces/IMapleLoanFactory.sol
> +interface IMapleLoanFactory {
That will need to be its own PR, as it was not the intention of this PR.

2021-09-17 15:43 UTC, merged