feat: Lend unit tests (SC-3752)
maple-labs/loan pull request #23
Opened 2021-09-14 21:35 UTC by JGcarv

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-09-15 01:22 UTC, lucas-manuel requested changes
Good testing, some minor changes

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +    LoanPrimitiveHarness loan;
Lets move out the `LoanPaymentBreakDownTest` into a separate file, and make this file use the `Loan` itself, not the harness. A lot of this logic can just be moved over and used with the actual Loan, but this test should be unit testing the Loan itself.

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        token = new MockERC20("FundsToken", "FT", 0);
Alignment and alphabetical

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +    LoanPrimitiveHarness loan;
Alignment and alphabetical by Contract type

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        address[2] memory assets = [ address(mockCollateralTokenl), address(token)];
Space beside bracket

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        token.mint(address(lender),   5_000_000);
Extra space

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        assertEq(loan.getUnaccountedAmount(address(token)), 1_000_000);
I know it can seem redundant, but I think for functions like this we should do the before state. It makes it abundantly clear what state is changing and ensures that we never miss anything.

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        lender.erc20_transfer(address(token), address(loan), 1_000_000);
Before state here for `getUnaccountedAmount`

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +
Before state here for `lender`

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        assertEq(address(0), loan.lender());
`assertEq(loan.lender(), address(0));`

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        assertEq(address(0), loan.lender());
`assertEq(loan.lender(), address(0));`

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        lender.erc20_transfer(address(token), address(loan), 500_000);
For cases like this, we should use `1_000_000 - 1` or `999_999`

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        lender.erc20_transfer(address(token), address(loan), 500_000);
Always test at the exact bounds

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +    }
For these tests where we're asserting failures, lets use the `testFail` function type

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        // I think this should go through and the excess amount stays available for claiming by lender
Yeah this is interesting, we should discuss

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +import { Lender }     from "./accounts/Lender.sol";
`import { Lender } from "./accounts/Lender.sol";`

2021-09-15 01:22 UTC, lucas-manuel commented on contracts/test/harnesses/LoanPrimitiveHarness.sol
> +    function lend(address lender_) external returns (uint256 amount_) {
We can revert all of these changes since we won't need them for the Loan unit testing

2021-09-15 12:35 UTC, satyamakgec commented on contracts/test/Loan.t.sol
> +import { MockERC20 } from "../../modules/erc20/src/test/mocks/MockERC20.sol";
If I am not wrong all the similar import paths should be club together.

2021-09-15 12:35 UTC, satyamakgec commented on contracts/test/Loan.t.sol
> +import { MockERC20 } from "../../modules/erc20/src/test/mocks/MockERC20.sol";
ref - https://github.com/maple-labs/smart-contract-standards/blob/main/sections/style-guide.md#imports

2021-09-15 13:12 UTC, JGcarv commented on contracts/test/Loan.t.sol
> +    }
I though about this, but I think `testFail` passes with a revert anywhere in the function, and while in most cases we're pretty sure that is reverting in the right place, there's no way to be 100% sure.

2021-09-15 13:42 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +        assertEq(loan.getUnaccountedAmount(address(token)), 1_000_000);
I agree, but only for what is relevant to that function. So in this case, we expect the unaccounted amount of funds asset to be 0 at the start, and then after a transfer, for it to be some new amount, as is currently done.

2021-09-15 14:24 UTC, lucas-manuel requested changes
Small comments, after that lgtm

2021-09-15 14:24 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +    address constant mockCollateralTokenl = address(9);
`mockCollateralToken`

2021-09-15 14:24 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        token      = new MockERC20("FundsToken", "FT", 0);
```js
lender = new Lender();
loan   = new LoanPrimitiveHarness();
token  = new MockERC20("FundsToken", "FT", 0);
```

2021-09-15 14:24 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +            uint256(100_000),
I think for this we should use `1_200 * 100` or `12_0000` for these scaled basis points values

2021-09-15 14:24 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        lender.erc20_transfer(address(token), address(loan), 1_000_000);
@deluca-mike is right, I think we should actually only assert the before state for the function that we are specifically testing. So what you have in the above function is perfect, and then for this we would check the `lender` and `getUnaccountedAmount` before state before the `lend` but we don't need it before the transfer

2021-09-15 14:24 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        assertEq(loan.lender(),                           address(0));
```js
assertEq(loan.getUnaccountedAmount(address(token)), 1_000_000);
assertEq(loan.lender(),                             address(0));
```

2021-09-15 14:33 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +        token      = new MockERC20("FundsToken", "FT", 0);
`token = new MockERC20("FundsAsset", "FA", 0);

2021-09-15 14:35 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +            uint256(100_000),
`1_200 * 100`

2021-09-15 14:42 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +        lender.erc20_transfer(address(token), address(loan), 1_000_000);
It's not really what I meant. See, `getUnaccountedAmount` is returns based on logic, so testing `getUnaccountedAmount` at different contract states, is important. There is no "before".

In the case of a lend, we _know_ that hevm testing results in a fresh state and the `setup` for each test, so testing the initial state is not only irrelevant to what `lend` does, but also redundant, as we put it in that state in the `setup`.

I don't agree that `assertEq(loan.getUnaccountedAmount(address(token)), 0);` is needed here, the same way I don't agree that `assertEq(erc20.balanceOf(address(user)), 0);` is needed at the start of a test of a transfer of erc20, in an erc20 repo.

2021-09-15 14:48 UTC, deluca-mike requested changes
I disagree with "before" assertions.

2021-09-15 14:48 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +    function test_lend_with_zero_amount() external {
```suggestion
    function test_lend_withZeroAmount() external {
```

2021-09-15 14:48 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +    function test_lend_sending_extra() external {
```suggestion
    function test_lend_sendingExtra() external {
```

2021-09-15 14:48 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +    }
```suggestion
    function testFail_lend_claimImmediatelyAfterLend() external {
        lender.erc20_transfer(address(token), address(loan), 1_000_000);
        lender.loan_lend(address(loan), address(lender))
        
        assertTrue(lender.try_loan_claimFunds(address(loan), 1_000_000, address(this)));
    }
```

2021-09-16 03:57 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +import { MockERC20 } from "../../modules/erc20/src/test/mocks/MockERC20.sol";
That is what's going on here, though.

2021-09-16 03:59 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +contract LoanPaymentBreakDownTest is DSTest {
Might need to pop out `test_getFee` and `test_getInstallment` into separate test contract if we're going to call it this.

2021-09-16 14:15 UTC, JGcarv commented on contracts/test/Loan.t.sol
> +contract LoanPaymentBreakDownTest is DSTest {
I think you're right. but I think this would fit better in a separate PR

2021-09-16 14:55 UTC, lucas-manuel requested changes
Small changes

2021-09-16 14:55 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +contract LoanPaymentBreakDownTest is DSTest {
Lets add a TODO to capture this

2021-09-16 14:55 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +    }
We can keep this form now, but I think we're going to want to steal the constrictToRange(val, min, max) that was used in the original fuzz tests in the future.

2021-09-16 14:55 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +    }
Nice

2021-09-16 14:55 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +    function test_lend_getUnnacountedAmount(uint amount) external {
amount_

2021-09-16 14:55 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +
Should have before state of `getUnaccountedAmount`

2021-09-16 14:55 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +
Remove breakline

2021-09-16 14:55 UTC, lucas-manuel commented on contracts/test/harnesses/LoanPrimitiveHarness.sol
> +    /**************************/
Nice

2021-09-16 16:19 UTC, JGcarv commented on contracts/test/Loan.t.sol
> +
I thought we weren't doing before state assertions, why would we need it here?

2021-09-16 16:28 UTC, lucas-manuel commented on contracts/test/Loan.t.sol
> +
We should add it here since its not an initial state, it went from zero => requestedAmount, and will go back to zero

2021-09-16 19:47 UTC, deluca-mike commented on contracts/test/Loan.t.sol
> +
Disagree a bit. `test_lend_getUnnacountedAmount` already tests this.

2021-09-16 19:49 UTC, deluca-mike approved these changes

2021-09-16 19:51 UTC, deluca-mike approved these changes

2021-09-16 20:40 UTC, lucas-manuel approved these changes

2021-09-16 20:40 UTC, merged