feat: Makepayment test (SC-3754)
maple-labs/loan pull request #36
Opened 2021-09-21 13:04 UTC by JGcarv

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-09-21 15:15 UTC, deluca-mike commented on contracts/test/LoanPrimitive.t.sol
> +    uint256 constant MAX_TIME = 10 * 365 days; // Assumed reasonable upper limit for payment intervals and grace periods
```suggestion
    uint256 constant MAX_TIME = 10 * 365 days;  // Assumed reasonable upper limit for payment intervals and grace periods
```

2021-09-21 15:16 UTC, deluca-mike commented on contracts/test/LoanPrimitive.t.sol
> +        uint256 endingPrincipal = _constrictToRange(endingPrincipal_, 0, PRINCIPAL_REQUESTED);
Can reuse stack item `endingPrincipal_` as `endingPrincipal_` is no longer used, and just makes sense as to reduce chances of `STACK_TOO_DEEP`.
```suggestion
    {
        uint256 endingPrincipal_ = _constrictToRange(endingPrincipal_, 0, PRINCIPAL_REQUESTED); 
```

2021-09-21 15:19 UTC, deluca-mike commented on contracts/test/LoanPrimitive.t.sol
> +        uint256 numberOfPayments = _constrictToRange(numberOfPayments_, 1, paymentsRemaining);
Same for all of these. Just overwrite the input.

2021-09-21 15:19 UTC, deluca-mike commented on contracts/test/LoanPrimitive.t.sol
> +        assertEq(loan.principal(), PRINCIPAL_REQUESTED);
```suggestion
        assertEq(loan.drawableFunds(),  0);
        assertEq(loan.claimableFunds(), 0);
        assertEq(loan.principal(),      PRINCIPAL_REQUESTED);
```

2021-09-21 15:23 UTC, lucas-manuel requested changes

2021-09-21 15:23 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +    uint256 constant MAX_TIME = 10 * 365 days; // Assumed reasonable upper limit for payment intervals and grace periods
Should use `10_000 * 365 days` as upper bound. 10 days is too small

2021-09-21 15:23 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +    uint256 constant PRINCIPAL_REQUESTED = 1_000_000;
Should use one
```js
uint256 constant MAX_TOKEN_AMOUNT = 1e12 * 10 ** 18;  // 1 trillion of a token with 18 decimals (assumed reasonable upper limit for token amounts)
``` 
value

2021-09-21 15:23 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        uint256 numberOfPayments_
Need to fuzz `collateralRequired_` and `principalRequested_`

2021-09-21 15:23 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        uint256 numberOfPayments_
And constrict them to `0, MAX_TOKEN_AMOUNT`

2021-09-21 15:23 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        uint256 endingPrincipal   = _constrictToRange(endingPrincipal_,   0,   PRINCIPAL_REQUESTED);
`0, principalRequested`

2021-09-21 15:23 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        assertEq(loan.paymentsRemaining(),  paymentsRemaining - numberOfPayments);
UPdate assertions accordingly

2021-09-21 15:23 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        assertEq(loan.collateral(),         COLLATERAL_REQUIRED);
Don't need collateral assertion

2021-09-21 18:44 UTC, lucas-manuel requested changes

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        lateFeeRate_        = _constrictToRange(lateFeeRate_,        0,   10_000);
10_000 * 100

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> -    function _initializeLoanWithCollateralRequested(uint256 collateralRequested_) internal {
`_initializeLoanWithCollateralRequired`

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +    function _initializeLoanWithpaymentsRemaining(uint256 paymentsRemaining_) internal {
WithPayments

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        hevm.warp(start + paymentInterval_ * numberOfPayments_);
We don't need this warp

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +    function test_makePayment(
makePayments

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        //Only 1 payment to do
// Only

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        //Only 1 payment to do
Actually not sure what this comment means

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        //Provide more than enough tokens
// Provide

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        uint256 start = block.timestamp;
We don't need start

2021-09-21 18:44 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        try loan.makePayments(paymentsRemaining_ + 1) { assertTrue(false);} catch {assertTrue(true);}
Spaces on either side of {}: `{ assertTrue(false); }`, empty block for `catch`
```js
try loan.makePayments(paymentsRemaining_ + 1) { assertTrue(false); } catch {}
```

2021-09-21 19:37 UTC, deluca-mike commented on contracts/LoanPrimitive.sol
> +        _nextPaymentDueDate += _paymentInterval * numberOfPayments_;
💯

2021-09-22 17:28 UTC, deluca-mike approved these changes

2021-09-23 14:12 UTC, merged