feat: Update Loan functions for integration (SC-3845)
maple-labs/loan pull request #43
Opened 2021-09-22 20:52 UTC by lucas-manuel

# Description

Add missing functions to make integrations work.

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-09-22 23:03 UTC, deluca-mike requested changes

2021-09-22 23:03 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +    // TODO: Investigate removing `factory()`
👍

2021-09-22 23:03 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +    // TODO: Remove this once new DebtLocker is in place
👍

2021-09-22 23:03 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +    mapping(address => bool)    public override isLoan;  // TODO: add interface
Add a `TODO: look into removing` since I am not convinced this is needed, especially in a contract that cannot be upgraded.

2021-09-22 23:03 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        isLoan[loan_] = true;
Same `TODO` here.

2021-09-22 23:03 UTC, deluca-mike commented on contracts/interfaces/IMapleLoan.sol
> +
TODO here too.

2021-09-22 23:03 UTC, deluca-mike commented on contracts/interfaces/IMapleLoanFactory.sol
> +
TODO here too.

2021-09-23 14:14 UTC, lucas-manuel commented on contracts/MapleLoanFactory.sol
> +    mapping(address => bool)    public override isLoan;  // TODO: add interface
This is our issue https://github.com/maple-labs/pool/blob/b2ef43ef93b16ed71c3689f764c24f6b2b2e4d42/contracts/libraries/PoolLib.sol#L86

2021-09-23 14:15 UTC, lucas-manuel commented on contracts/MapleLoan.sol
> +    // TODO: Investigate removing `factory()`
I think we're gonna have to keep `superFactory`: https://github.com/maple-labs/pool/blob/b2ef43ef93b16ed71c3689f764c24f6b2b2e4d42/contracts/libraries/PoolLib.sol#L82

2021-09-23 15:48 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +    // TODO: Investigate removing `factory()`
I guess it's fine. It's just interface and can be upgraded out.

2021-09-23 15:58 UTC, deluca-mike requested changes

2021-09-23 15:58 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +    mapping(address => bool)    public override isLoan;  // TODO: add interface
I would rather create a more useful `indexOfLoan` that returns the index of a loan address within `loanAtIndex`, so that way have. two-way mapping, and then expose a `isLoan` function that does:
```js
function isLoan(address loan_) external returns (bool isLoan_) {
    return loanAtIndex[indexOfLoan[loan_]] == loan_;
}
```
if we're going to create a mapping and consume storage slots and gas, might as well make it more generic and useful than some bools.

2021-09-23 15:58 UTC, deluca-mike commented on contracts/MapleLoanFactory.sol
> +        isLoan[loan_] = true;
```suggestion
        indexOfLoan[loan_] = loanCount;
```

2021-09-24 19:46 UTC, closed without merging