feat: Add collateral minted test (SC-3851)
maple-labs/loan pull request #46
Opened 2021-09-24 13:58 UTC by satyamakgec

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-09-24 19:57 UTC, deluca-mike requested changes

2021-09-24 19:57 UTC, deluca-mike commented on contracts/test/LoanPrimitive.t.sol
> +    function test_collateralMaintained(uint256 amount_, uint256 collateral_, uint256 numberOfPayments_, uint256 fundedAmount_) external {
This test isn't really testing much since the loan is not possible t be put into a state where the collateral ratio is not maintained. A proper test would be to set up the state such that it can be tested against expected results of the collateral ratio being maintained or not.

Or, to make the `collateralMaintained` function pure, so that it's logic can be unit tested separately.

2021-09-27 16:28 UTC, lucas-manuel requested changes
Run a `dapp update` on this branch, I don't think the proxy-factory should change

2021-09-27 16:28 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +        loan            = new LoanPrimitiveHarness();
Extra spaces

2021-09-27 16:28 UTC, lucas-manuel commented on contracts/LoanPrimitive.sol
> +    {
) 
        internal pure
        returns (bool isMaintained_) 
    {

2021-09-27 16:28 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +    function test_collateralMaintained_collateralIsHigh() external {
We need to test the edges of this condition, it should be
`LHS == RHS` then reduce `_collateral` by one so it is `LHS < RHS`
`LHS == RHS` then increment `_drawableFunds` by one so it is `LHS < RHS`

2021-09-27 16:28 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +            "Fails to maintain collateral"
Wrong error message

2021-09-27 16:28 UTC, lucas-manuel commented on contracts/test/LoanPrimitive.t.sol
> +            "Fails to maintain collateral"
Wrong error message

2021-09-28 16:53 UTC, deluca-mike approved these changes

2021-09-28 16:54 UTC, merged