feat: Add payments tests against CSV values (SC-3899 + SC-3900 + SC-3901)
maple-labs/loan pull request #52
Opened 2021-09-30 18:09 UTC by lucas-manuel

# Description

Add payments tests for interest only, partially amortized, and fully amortized loans against the sheet provided by the business team: https://docs.google.com/spreadsheets/d/1C_zhjPs_s_IBnDYBOdrfF2jd59vLAEXumN49YbmTJns/edit#gid=1232787594

All payments are made on time.

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-09-30 23:20 UTC, lucas-manuel commented on contracts/test/Payments.t.sol
> +        // TODO: Add final balance variable
Conflicted on whether this is really necessary, lmk what you guys think

2021-10-01 13:14 UTC, lucas-manuel commented on contracts/test/Payments.t.sol
> +        /****************************************/
Just noticed these are misaligned, will push a fix soon

2021-10-01 15:00 UTC, deluca-mike commented on contracts/test/Payments.t.sol
> +        // TODO: Add final balance variable
I would do it just for completeness.

2021-10-01 15:01 UTC, deluca-mike commented on contracts/test/Payments.t.sol
> +        /****************************************/
Make sure to "Remove Trailing Whitespaces" in VS Code.

2021-10-01 15:01 UTC, deluca-mike commented on contracts/test/Payments.t.sol
> +        /****************************************/
```suggestion
    function test_payments_fullyAmortized_case2() external {
        /****************************************/
```
and the rest as well.

2021-10-01 15:04 UTC, JGcarv requested changes

2021-10-01 16:19 UTC, deluca-mike approved these changes

2021-10-01 16:21 UTC, merged