feat: Add Refinance for static terms + tests (SC-3905)
maple-labs/loan pull request #53
Opened 2021-09-30 20:22 UTC by JGcarv

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-10-01 13:50 UTC, lucas-manuel requested changes

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/MapleLoan.sol
> +        refinanceHash = keccak256(abi.encodePacked(refinancer_, arguments_));
We're going to want an event for this, otherwise it will be hard for the lender to pass in the same args. In terms of the app, we can render the proposal using the event and then the lender can just accept

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/MapleLoan.sol
> +
Extra line

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/harnesses/MapleLoanHarness.sol
> +        (bool success, ) = refinancer_.delegatecall(arguments_);
`( bool success, )`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +        (uint8[] memory codes, bytes[] memory datas) = abi.decode(msg.data, (uint8[],bytes[]));
`( uint8[] memory codes, bytes[] memory datas )`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +import { LoanPrimitive} from "./LoanPrimitive.sol";
`{ LoanPrimitive }`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    /******************+****/
Format

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    /*******************/
Format

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +                continue;
We can get rid of the `continue`s

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    // Increase the collateral - It needs to be posted by borrower beforehand
before drawdown

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    function _increaseCollateral(uint256 newCollateral_) internal {
_increaseCollateralRequired

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    function _increasePrincipal(uint256 newAmount_) internal {
_increasePrincipalRequested

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    }
What do we think of `_update` instead of `_change`?

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +contract BaseTest is TestUtils, StateManipulations {
`BaseRefinanceTest`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        {
Format

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +            // Ending Principal
We should have a quick discussion on what the best way to approach this function is, I feel like theres a few options

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +    function setUpOngoinLoan(
`setUpOngoingLoan`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        args[0] = abi.encode(arg_);
Align

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +    function test_refinance_endingPrincipal_InterestOnlyToAmortized(
`interestOnlyToAmortized`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        principalRequested_ = constrictToRange(principalRequested_, MAX_TOKEN_AMOUNT / 10, MAX_TOKEN_AMOUNT); // Boundary increase so principal portion on 'paymentBreakdown' is always greater than 0
The lower bound here should be zero or a much lower number, like 10 ** 6

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        setUpOngoinLoan(principalRequested_, collateralRequired_,principalRequested_,gracePeriod_, interestRate_,lateFeeRate_,paymentInterval_,paymentsRemaining_);
Space formatting

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        uint256 newEnding_
`newEndingPrincipal_`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        loan.acceptNewTerms(address(refinancer), data_);
Formatting

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        principalRequested_ = constrictToRange(principalRequested_, MAX_TOKEN_AMOUNT / 10, MAX_TOKEN_AMOUNT); // Boundary increase so principal portion on 'paymentBreakdown' is always greater than 0
Lower lower bound

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        setUpOngoinLoan(principalRequested_, collateralRequired_,endingPrincipal_,gracePeriod_,interestRate_,lateFeeRate_,paymentInterval_,paymentsRemaining_);
Space formatting

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        uint256 newEnding_ = loan.principal();
newEndingPrincipal_

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        loan.acceptNewTerms(address(refinancer), data_);
Align

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        setUpOngoinLoan(principalRequested_, collateralRequired_,endingPrincipal_,gracePeriod_,interestRate_,lateFeeRate_,paymentInterval_,paymentsRemaining_);
Space formatting

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        loan.acceptNewTerms(address(refinancer), data_);
Align

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        assertEq(loan.gracePeriod(),gracePeriod_);
Space

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        principalRequested_ = constrictToRange(principalRequested_, MAX_TOKEN_AMOUNT / 10, MAX_TOKEN_AMOUNT);
Lower lower bound

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        newGracePeriod_ = constrictToRange(newGracePeriod_, 0, 99);
`constrictToRange(newGracePeriod_, 0, MAX_TIME);` - doesnt have to be less

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        setUpOngoinLoan(principalRequested_, collateralRequired_,endingPrincipal_,gracePeriod_,interestRate_,lateFeeRate_,paymentInterval_,paymentsRemaining_);
Space formatting

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        ( ,uint256 currentInterestPortion , ) = loan.getNextPaymentsBreakDown(1);
`( , uint256 currentInterestPortion , )`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        loan.acceptNewTerms(address(refinancer), data_);
Align

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        assertEq(loan.interestRate(),interestRate_);
Space

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +    function test_refinance_interestRate_decrease(
We probably don't need this test, can just do a set in the first test

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        newInterestRate_ = constrictToRange(newInterestRate_, MAX_RATE / 2 + 1, MAX_RATE);
`constrictToRange(newInterestRate_, 0, MAX_RATE);`, interest can be any value

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        ( ,uint256 newInterestPortion , ) = loan.getNextPaymentsBreakDown(1);
`( , uint256 newInterestPortion , )`

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        newPaymentInterval_ = constrictToRange(newPaymentInterval_, MAX_TIME / 2 + 1, MAX_TIME);
`newPaymentInterval_ = constrictToRange(newPaymentInterval_, 0, MAX_TIME);` Can make paymetn interval any value

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        setUpOngoinLoan(principalRequested_, collateralRequired_,endingPrincipal_,gracePeriod_,interestRate_,lateFeeRate_,paymentInterval_,paymentsRemaining_);
Spaces

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +        loan.acceptNewTerms(address(refinancer), data_);
Align

2021-10-01 13:50 UTC, lucas-manuel commented on contracts/test/Refinancer.t.sol
> +contract RefinanceMultipleParameterTest is BaseTest {
Nice test

2021-10-01 19:42 UTC, deluca-mike requested changes
made some suggestions to do this simpler, without "codes", two arrays, a code lookup, or a fallback.

2021-10-01 19:42 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +    bytes32 refinanceHash;
```suggestion
    bytes32 public refinanceCommitment;
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    }
`_set`

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +        require(_isCollateralMaintained());
Don't need this. Collateral only has to be checked to be maintained when the borrower is drawing down or removing collateral.

2021-10-01 19:42 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +    function proposeNewTerms(address refinancer_, bytes calldata arguments_) external override {
```suggestion
    function proposeNewTerms(address refinancer_, bytes[] calldata calls_) external override {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +    function acceptNewTerms(address refinancer_, bytes calldata arguments_) external override {
```suggestion
    function acceptNewTerms(address refinancer_, bytes[] calldata calls_) external override {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +        require(success, "ML:ANT:FAILED");
```suggestion
        for (uint256 i; i < calls_.length; ++i) {
            ( bool success, ) = refinancer_.delegatecall(calls_[i]);
            require(success, "ML:ANT:FAILED");
        }
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/test/harnesses/MapleLoanHarness.sol
> +contract MapleLoanHarness is LoanPrimitiveHarness {
This isn't a harness.

Either
```suggestion
contract MapleLoanMock is MapleLoan {
```
and override the function to remove the ACL?

Or, just use lender and borrower accounts so that we don't need a harness that isn't really a harness.

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    function _changeEndingPrincipal(uint256 newEndingPrincipal_) internal {
```suggestion
    function setEndingPrincipal(uint256 newEndingPrincipal_) external {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    function _changeGracePeriod(uint256 newGracePeriod_) internal {
```suggestion
    function setGracePeriod(uint256 newGracePeriod_) external {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    function _changeInterestRate(uint256 newInterestRate_) internal {
```suggestion
    function setInterestRate(uint256 newInterestRate_) external {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    function _changePaymentInterval(uint256 newInterval_) internal {
```suggestion
    function setPaymentInterval(uint256 newInterval_) external {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    function _increasePrincipal(uint256 newAmount_) internal {
```suggestion
    function setPrincipalRequested(uint256 newAmount_) external {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    function _increaseCollateral(uint256 newCollateral_) internal {
```suggestion
    function setCollateralRequested(uint256 newCollateral_) external {
```

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    function _execute(uint8[] memory funcs_, bytes[] memory args_) internal {
Don't need `_execute`

2021-10-01 19:42 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    fallback() external {
Don't need a fallback.

2021-10-04 19:07 UTC, deluca-mike requested changes

2021-10-04 19:07 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    }
Can't change `_principal` this way as it is based on how much is left to be rapayed, which depends on how much was actually lent to the contract.
```suggestion
    function setPrincipalRequested(uint256 principalRequested_) external {
        if (principalRequired_ >= _principalRequested) {
            // Perhaps do this as its own `handleIncreasedPrincipalRequested`
            uint256 increase = principalRequested_ - _principalRequested;
            require(_getUnaccountedAmount(_fundsAsset) >= increase);

            _drawableFunds      += increase;
            _principal          += increase;
            _principalRequested += increase;
            return;
        }

        // Perhaps do this as its own `handleDecreasedPrincipalRequested`
        uint256 decrease = _principalRequested - principalRequested_;
        require(_drawableFunds >= decrease);
        require(_principal     >= decrease);

        _drawableFunds      -= decrease;
        _principal          -= decrease;
        _principalRequested -= decrease;
    }
```

2021-10-04 19:13 UTC, deluca-mike requested changes

2021-10-04 19:13 UTC, deluca-mike commented on contracts/MapleLoan.sol
> +        }
Also, needs a check that colateral is maintained here, since an increase of collateral required, or a decrease in principal requested, can result in a lack of collateral for a given outstanding principal.

2021-10-04 19:13 UTC, lucas-manuel reviewed
LGTM so far as well

2021-10-04 19:13 UTC, lucas-manuel commented on contracts/MapleLoan.sol
> +        refinanceCommitment = keccak256(abi.encode(refinancer_, calls_));
👍

2021-10-04 19:13 UTC, lucas-manuel commented on contracts/MapleLoan.sol
> +        }
👍

2021-10-04 19:13 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    }
👍

2021-10-04 19:13 UTC, lucas-manuel commented on contracts/Refinancer.sol
> +    }
Yeah I think having two functions here makes sense

2021-10-04 20:13 UTC, JGcarv commented on contracts/Refinancer.sol
> +    }
That could make the loan under collateralized and the borrower might just never post it.  Imagine I have a 0% collateral loan, but the refinance will increase to 10% with a principal increase also. If I don't commit the collateral upfront, why should the lender refinance in the first place? He has no assurance that I'll ever do post the extra amount required

2021-10-04 20:28 UTC, JGcarv commented on contracts/Refinancer.sol
> +    }
Nevermind, checking for isCollateralMaintained in maple loan prevents that

2021-10-04 20:51 UTC, JGcarv commented on contracts/Refinancer.sol
> +    }
```
        if (principalRequired_ >= _principalRequested) {
            // Perhaps do this as its own `handleIncreasedPrincipalRequested`
            uint256 increase = principalRequested_ - _principalRequested;
            require(_getUnaccountedAmount(_fundsAsset) >= increase);
            _drawableFunds      += increase;
            _principal          += increase;
            _principalRequested += increase;
            return;
        }
```

Isn't this identical to what the original function does? But instead of passing absolute amounts, the parameter is the increase?

2021-10-05 02:05 UTC, deluca-mike commented on contracts/Refinancer.sol
> +    }
Ya, the different is now the argument is the amount to set to, not to increase by.

2021-10-05 16:21 UTC, merged