feat: Added unit test for access control
maple-labs/loan pull request #84
Opened 2021-11-18 16:36 UTC by JGcarv

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-11-18 19:23 UTC, lucas-manuel requested changes

2021-11-18 19:23 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +    function test_acessControl_setImplementation() external {
`accessControl` for all tests

2021-11-18 19:23 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        try loan.setImplementation(address(this)) { assertTrue(false, "non factory was able to set implementation"); } catch { }
`Non-factory` - apply to all error messages (`Non-borrower`, etc)

2021-11-18 19:23 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        try loan.migrate(address(this), new bytes(0)) { assertTrue(false, "non factory was able to migrate"); } catch { }
For every one of these try/catches we should have a line right after that demonstrates the successful ACL. This will require us to add a slot setter for factory, borrower and lender in the MapleLoan

2021-11-18 19:37 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        try loan.migrate(address(this), new bytes(0)) { assertTrue(false, "non factory was able to migrate"); } catch { }
Added this in DL, can do the same in ManipulatableMapleLoan:

```js
    function setFactory(address factory_) external {
        _setSlotValue(FACTORY_SLOT, bytes32(uint256(uint160(factory_))));
        return true;
    }
    ```

2021-11-19 20:28 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        address refinancer = address(0);
Lets keep `address(1)`, I like using non-zero addresses where we aren't explicitly using a zero address, to avoid confusion

2021-11-19 20:32 UTC, lucas-manuel requested changes
Small changes

2021-11-19 20:32 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        loan.setBorrower(address(this));
Should set to address(1), since its already address(this)

2021-11-19 20:32 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        loan.acceptNewTerms(refinancer, data, uint(9));
Should be uint256(0)

2021-11-19 20:32 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
>          loan.setClaimableFunds(uint256(200_00));
200_000

2021-11-19 20:32 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
>      function test_accessControl_reposses() external {
repossess

2021-11-19 20:32 UTC, lucas-manuel commented on contracts/test/MapleLoan.t.sol
> +        hevm.warp(100);
`hevm.warp(loan.nextPaymentDueDate() + loan.gracePeriod() + 1)`

2021-11-24 19:56 UTC, deluca-mike submitted a review, later dismissed

2021-11-25 22:26 UTC, merged