fix: DoS prevention in `fundLoan` and `acceptNewTerms`
maple-labs/loan pull request #89
Opened 2021-11-23 08:28 UTC by deluca-mike

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

## Function Signature Changes

## Features

## Events

2021-11-23 16:26 UTC, lucas-manuel commented
Addresses https://github.com/maple-labs/trail-of-bits-audit/issues/8

2021-11-24 15:23 UTC, lucas-manuel requested changes
Lets add a quick test in MapleLoan.t.sol with ConstructableMapleLoan and do an external `fundLoan` call with extra funds, and another with nextPaymentDueDate > 0

2021-11-25 06:28 UTC, deluca-mike commented
> Lets add a quick test in MapleLoan.t.sol with ConstructableMapleLoan and do an external `fundLoan` call with extra funds, and another with nextPaymentDueDate > 0

tests done for funding and accepting new terms with extra amount, with `ManipulatableMapleLoan`.

2021-11-25 14:24 UTC, lucas-manuel requested changes

2021-11-26 17:22 UTC, merged